In [1]:
a=1
print(a)

1


In [2]:
a=int(input("enter first number"))
b=int(input("enter second number"))
sum=a+b
print(sum)


enter first number3
enter second number4
7


In [3]:
a="abc"
type(a)

str

In [4]:
def function():
    mark1=30
    mark2=35
    mark3=50
    sum=mark1+mark2+mark3
    avg=(mark1+mark2+mark3)/3
    return sum,avg
    



In [5]:
function()

(115, 38.333333333333336)

In [6]:
def function1(m1,m2,m3):
    sum=m1+m2+m3
    avg=(m1+m2+m3)/3
    return sum,avg

In [7]:
function1(3,4,5)

(12, 4.0)

In [8]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [9]:
for i in range(10,0,-1):
    print(i)

10
9
8
7
6
5
4
3
2
1


In [10]:
import math
r=2
r=math.pi*r*r
print(r)

12.566370614359172


In [11]:
from package import pack
pack.sum(6,2)


8


In [12]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [13]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
r=np.arange(0,10,2)
r

array([0, 2, 4, 6, 8])

In [15]:
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [16]:
a-b

array([-3, -3, -3])

In [17]:
np.mean(a)

2.0

In [18]:
np.max(a)

3

In [19]:
c=np.array([
    [1,2],
    [3,4]
])

In [20]:
c

array([[1, 2],
       [3, 4]])

In [21]:
d=np.array([
    [4,8],
    [6,9]
])


In [22]:
c+d

array([[ 5, 10],
       [ 9, 13]])

In [23]:
c*d

array([[ 4, 16],
       [18, 36]])

In [24]:
a*b

array([ 4, 10, 18])

In [25]:
e=c*d
e

array([[ 4, 16],
       [18, 36]])

In [26]:
f=np.dot(c,d)
f

array([[16, 26],
       [36, 60]])

In [27]:
f.T


array([[16, 36],
       [26, 60]])

In [28]:
print("\n matrix 1:\n",c)
print("\n matrix 2:\n",d)
print("\n addition:\n",c+d)
print("\n substraction:\n",c-d)
print("\n multiplication (element wise):\n",c*d)
print("\n multiplication (row x column):\n",f)
print("\n transpose:\n",f.T)


 matrix 1:
 [[1 2]
 [3 4]]

 matrix 2:
 [[4 8]
 [6 9]]

 addition:
 [[ 5 10]
 [ 9 13]]

 substraction:
 [[-3 -6]
 [-3 -5]]

 multiplication (element wise):
 [[ 4 16]
 [18 36]]

 multiplication (row x column):
 [[16 26]
 [36 60]]

 transpose:
 [[16 36]
 [26 60]]


In [29]:
c

array([[1, 2],
       [3, 4]])